config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  post '/posts/:post_id/comments/:id' => 'comments#reveal', :as => 'reveal'
  post '/users/:user_id' => 'users#promote', :as => 'promote'

  root to: 'mainpages#index'
  resources :user_sessions
  resources :users
  resources :mainpages
  resources :posts do
    resources :comments
  end

  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!

  validates :password, length: { minimum: 4 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }

  validates :email, uniqueness: true, length: { minimum: 4 }
  validates :more, length: { maximum: 300 }
  has_many :posts
  
  ratyrate_rater
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  skip_before_action :require_login, only: [:index, :new, :create]

  load_and_authorize_resource except: [:set_user, :user_params, :promote]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to :login, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to :action => 'index', notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def promote
    @user = User.find(params[:user_id])
    @user.adminrights = true
    @user.save
    redirect_to @user
  end

  private

    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation, :more, :adminrights)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nickname %>
    <%= f.text_field :email %>
  </div>

  <div class="field">
    <%= f.label :about %>
    <%= f.text_field :more, :size => '40x13' %>
  </div>

  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>

  <div class="field">
    <%= f.label :confirm_new_password %>
    <%= f.password_field :password_confirmation %>
  </div>

  Administrator? (this option is only in this demo mode of app)<br>
  <table>
    <tr>
      <td><%= f.label 'administrator_true', 'Yes' %></td>
      <td><%= f.radio_button :adminrights, true %></td>
    </tr>

    <tr>
      <td><%= f.label 'administrator_false', 'No' %></td>
      <td><%= f.radio_button :adminrights, false, :checked => true %></td>
    </tr>
  </table>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<% if current_user %>
  <% if can? :destroy, User or current_user.id == @user.id %>
      <h1>Editing User</h1>  
      <%= render 'form', user: @user %>
  <% else %>
    You can only edit your own profile!
  <% end %>
<% else %>
  You are not logged in!
<% end %>
<br><br>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Registered users</h1>
<br>
These people are registered on our site!<br>
<br><br>
<table>
  <thead>
    <tr>
      <th>Nickname</th>
      <th>About</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= user.more %></td>
        <% if current_user %>
          <td><%= link_to 'Show', user %></td>
          <% if can? :destroy, User or current_user.id == user.id %>
            <td><%= link_to 'Edit', edit_user_path(user) %></td>
          <% end %>
          <% if can? :destroy, User %>
            <td><%= link_to 'Delete', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if current_user %>
<%= link_to 'New user', new_user_path %>
<% end %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p>
  <strong>Nickname:</strong>
  <%= @user.email %><br> 
  <strong>Registered:</strong>
  <i><%= time_ago_in_words @user.created_at %> ago</i><br>
  <strong>Administrator?:</strong>
  <%= @user.adminrights ? "Yes" : "No" %><br> 
  <strong>About:</strong>
  <%= @user.more %>

<table>
  <thead>
    <tr>
      <p>
      <th>Title</th>
      <th>Text</th>
      <th>Created</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @user.posts.each do |post| %>
      <tr>
        <td><%= link_to post.title, post %></td>
        <td><%= truncate post.text %></td>
        <td><i><%= time_ago_in_words post.created_at %> ago</i>
        <td><%= link_to 'Show', post %></td>
        <% if current_user %>
        <% if current_user.adminrights %>
          <td><%= link_to 'Edit', edit_post_path(post) %></td>
          <td><%= link_to 'Delete', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

</p>
<% if current_user %>
  <% if can? :promote, User and !@user.adminrights %>
    <%= link_to 'Promote', user_path, method: :post %> |
  <% end %>
  <% if can? :destroy, User or current_user.id == @user.id %>
    <%= link_to 'Edit', edit_user_path(@user) %> |
  <% end %>
<% end %>
<%= link_to 'Back', users_path %>