config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  post '/posts/:post_id/comments/:id' => 'comments#reveal', :as => 'reveal'
  post '/users/:user_id' => 'users#promote', :as => 'promote'

  root to: 'mainpages#index'
  resources :user_sessions
  resources :users
  resources :mainpages
  resources :posts do
    resources :comments
  end

  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout
end

app/models/mainpage.rb
class Mainpage < ApplicationRecord
end

app/controllers/mainpages_controller.rb
class MainpagesController < ApplicationController
  before_action :set_mainpage, only: [:show, :edit, :update, :destroy]
  skip_before_action :require_login, only: [:index, :new, :create]

  # GET /mainpages
  # GET /mainpages.json
  def index
    @mainpages = Mainpage.all
  end

  # GET /mainpages/1
  # GET /mainpages/1.json
  def show
  end

  # GET /mainpages/new
  def new
    @mainpage = Mainpage.new
  end

  # GET /mainpages/1/edit
  def edit
  end

  # POST /mainpages
  # POST /mainpages.json
  def create
    @mainpage = Mainpage.new(mainpage_params)

    respond_to do |format|
      if @mainpage.save
        format.html { redirect_to @mainpage, notice: 'Mainpage was successfully created.' }
        format.json { render :show, status: :created, location: @mainpage }
      else
        format.html { render :new }
        format.json { render json: @mainpage.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mainpages/1
  # PATCH/PUT /mainpages/1.json
  def update
    respond_to do |format|
      if @mainpage.update(mainpage_params)
        format.html { redirect_to @mainpage, notice: 'Mainpage was successfully updated.' }
        format.json { render :show, status: :ok, location: @mainpage }
      else
        format.html { render :edit }
        format.json { render json: @mainpage.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mainpages/1
  # DELETE /mainpages/1.json
  def destroy
    @mainpage.destroy
    respond_to do |format|
      format.html { redirect_to mainpages_url, notice: 'Mainpage was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def set_mainpage
      @mainpage = Mainpage.find(params[:id])
    end

    def mainpage_params
      params.fetch(:mainpage, {})
    end
end

app/helpers/mainpages_helper.rb
module MainpagesHelper
end

app/views/mainpages/_form.html.erb
<%= form_for(mainpage) do |f| %>
  <% if mainpage.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(mainpage.errors.count, "error") %> prohibited this mainpage from being saved:</h2>

      <ul>
      <% mainpage.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/mainpages/edit.html.erb
<h1>Editing Mainpage</h1>

<%= render 'form', mainpage: @mainpage %>

<%= link_to 'Show', @mainpage %> |
<%= link_to 'Back', mainpages_path %>

app/views/mainpages/index.html.erb
<h1>Welcome to the game review website!</h1>

 
Here, you can read the newest game reviews and write your own ones, rate games, comment on them and simply have fun!<br>
<br>

View the posts and comment on them without having to register.<br>
Write your own posts, rate on posts of others, manage comments and see user details as a registered user.<br>
Administrators can edit or delete your post or even account if you don't act nicely!<br>
<br>

app/views/mainpages/new.html.erb
<h1>New Mainpage</h1>

<%= render 'form', mainpage: @mainpage %>

<%= link_to 'Back', mainpages_path %>

app/views/mainpages/show.html.erb
<%= link_to 'Edit', edit_mainpage_path(@mainpage) %> |
<%= link_to 'Back', mainpages_path %>