config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  post '/posts/:post_id/comments/:id' => 'comments#reveal', :as => 'reveal'
  post '/users/:user_id' => 'users#promote', :as => 'promote'

  root to: 'mainpages#index'
  resources :user_sessions
  resources :users
  resources :mainpages
  resources :posts do
    resources :comments
  end

  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments
  belongs_to :user
  ratyrate_rateable 'gameplay', 'graphics', 'story', 'uniqueness', 'addictiveness'

  def approval?
    commstats == 2 or commstats == 3
  end

  def enabled?
    commstats == 1 or commstats == 2
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:edit, :show, :update, :destroy]
  skip_before_action :require_login, only: [:index, :show]

  load_and_authorize_resource except: [:set_post, :post_params]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all

    respond_to do |format|
      format.html
      format.atom
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = current_user.posts.build(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private

    def set_post
      @post = Post.find(params[:id])
    end

    def post_params
      params.require(:post).permit(:title, :text, :commstats)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_for(post) do |f| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :text %>
    <%= f.text_area :text, :size => '60x15' %>
  </div>

  <table>
    <tr>
      <td><%= f.label 'Comments allowed', 'Comments allowed' %></td>
      <td><%= f.radio_button :commstats, 1, :checked => true %></td>
    </tr>

    <tr>
      <td><%= f.label 'Comments need approval', 'Comments need approval' %></td>
      <td><%= f.radio_button :commstats, 2 %></td>
    </tr>

    <tr>
      <td><%= f.label 'Comments not allowed', 'Comments not allowed' %></td>
      <td><%= f.radio_button :commstats, 3 %></td>
    </tr>
  </table>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<% if current_user %>
  <% if current_user.adminrights %> 
    <h1>Editing Post</h1>

    <%= render 'form', post: @post %>
  <% else %>
    Only administrators can edit a post.
  <% end %>
<% else %>
  You are not logged in!
<% end %>
<br><br>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>The game reviews</h1>

<br><br>

<% if current_user %>
<%= link_to 'New post', new_post_path %>
<% end %>

<table>
  <thead>
    <tr>
      <p>
      <th>Title</th>
      <th>Text</th>
      <th>Author</th>
      <th>Created</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= link_to post.title, post %></td>
        <td><%= truncate post.text %></td>
        <td><%= link_to post.user.email, post.user %></td>
        <td><i><%= time_ago_in_words post.created_at %> ago</i>
        <td><%= link_to 'Show', post %></td>
        <% if current_user %>
        <% if current_user.adminrights %>
          <td><%= link_to 'Edit', edit_post_path(post) %></td>
          <td><%= link_to 'Delete', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<br><br>
<% if current_user %>
<%= link_to 'New post', new_post_path %>
<% end %>

<br>

app/views/posts/new.html.erb
<% if current_user %>
<h1>New Post</h1>

<%= render 'form', post: @post %>
<% else %>
You are not logged in!
<% end %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<%= javascript_include_tag 'ratyrate.js', "data-turbolinks-track" => false %>
<p>
<h1><%= @post.title %></h1><br>
By <%= link_to @post.user.email, @post.user %>
</p>

<p>
<%= @post.text %>
</p>
<br>
<% if current_user %>
What do you think about this game? Rate it!<br>
<div class="row">
  <div class="small-2 large-4 columns">
      Gameplay: <%= rating_for @post, "gameplay", cancel_place: 'right', cancel_hint: 'Cancel this vote!', space: true, targetType: "score", disable_after_rate: false %>
      Graphics: <%= rating_for @post, "graphics", cancel_place: 'right', cancel_hint: 'Cancel this vote!', space: true, targetType: "score", disable_after_rate: false %>
      Story: <%= rating_for @post, "story", cancel_place: 'right', cancel_hint: 'Cancel this vote!', space: true, targetType: "score", disable_after_rate: false %>
      Uniqueness: <%= rating_for @post, "uniqueness", cancel_place: 'right', cancel_hint: 'Cancel this vote!', space: true, targetType: "score", disable_after_rate: false %>
      Addictiveness: <%= rating_for @post, "addictiveness", cancel_place: 'right', cancel_hint: 'Cancel this vote!', space: true, targetType: "score", disable_after_rate: false %>
      (Refresh this page to update)<br>
<br>
  </div>
</div>
<% else %>
Log in to see user rating and rate this game yourself!<br><br>
<% end %>


<%= link_to 'Back', posts_path %>
<% if current_user %>
<% if current_user.adminrights %> |
<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Delete post', @post, :method => :delete, :confirm => 'Are you sure?' %>
<% end %>
<% end %>
<br><br>
<h2>Comments</h2>

<% if @post.approval? %>
  <b>Comments need to be approved by a registered user on this post.</b><br><br>
<% end %>

<% if @post.enabled? %>
  <% @post.comments.each do |comment| %>
    <% if !@post.approval? or comment.shown or current_user %>
      <% if comment.user_email %>
        <b><%= comment.user_email %></b><br>
      <% else %>
        <b><i>Unregistered user</b></i><br>
      <% end %>
      <%= comment.text %><br>
      <i><%= time_ago_in_words comment.created_at %> ago</i><br>
      <% if @post.approval? and !comment.shown %>
        <%= link_to "Approve comment", [@post, comment], method: :post %> | 
      <% end %>
      <% if current_user %>
        <%= link_to "Delete comment", [@post, comment], method: :delete, data: {confirm: "Are you sure?" } %><br>
      <% end %><br>
    <% end %>
  <% end %>
<% else %>
  Comments are disabled on this post.<br><br>
<% end %>

<% if @post.enabled? %>
  <%= form_for [@post, @post.comments.build] do |f| %>
    <p><%= f.text_area :text, :size => '40x10' %></p>
    <% if current_user %>
      <%= f.hidden_field :user_email, value: current_user.email %>
    <% end %>
    <p><%= f.submit "Post comment" %></p>
  <% end %>
<% end %>